# This needs to be run from the root folder, and it behaves like it is from the root folder.

FROM python:3.10-slim
WORKDIR /app

COPY docker/docker-requirements.txt .
RUN pip install --no-cache-dir -r docker-requirements.txt

# Copy the project code (except the stuff listed in the .dockerignore)
COPY . .

CMD ["pytest", "tests/"]
